services:
  traefik:
    image: traefik
    ports: 
      - 443:443
      - 8080:8080
    command: 
      - --providers.docker
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8080
      - --api.dashboard=true
      - --api.insecure=true
    networks:
      - nt-traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nt-traefik:
    driver: bridge
